config/routes.rb
Rails.application.routes.draw do
  resources :links
  devise_for :users

  get '/:token', to: "links#explore"
  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  before_save :add_token
  validates :main_url, :presence => true


  def add_token
    if self.token.nil?
      self.token = rand(36**8).to_s(36)
    end
  end

  def redirection_url
    self.update(clicks: (self.clicks + 1))
    main_url
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]
  before_action :find_link, only: %i[ explore ]
  before_action :authenticate_user!, except: %i[explore]

  # GET /links or /links.json
  def index
    @links = current_user.links.order(clicks: :desc)
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.new
  end

  # POST /links or /links.json
  def create
    @link = current_user.links.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def explore
    if @link
      redirect_to @link.redirection_url, allow_other_host: true
    else
      redirect_to '/404'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    def find_link
      @link = Link.find_by(token: params[:token])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:main_url, :token)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper

  def short_url(link)
    "#{request.url.split("/#{params[:controller]}")[0]}/#{link.token}"
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag 'logo.png', { width: 30, height: 24, class: "d-inline-block align-text-top" } %>
      URL Shortner
    </a>

    <div class="dropdown show">
      <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-sm" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <div class="mb-3">
    <% if link.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

        <ul>
          <% link.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :main_url, class: "required-field" %>
      <%= form.text_field :main_url, class: "form-control", required: true  %>
    </div>

    <div>
      <%= form.label :alias, class: "form-label" %>
      <%= form.text_field :token, class: "form-control" %>
    </div>

    <br>

    <div>
      <div class="d-grid gap-2">
        <%= form.submit "Submit", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">

  <tr>
    <td scope="col">
      <%= link_to URI.parse(link.main_url).host, link.main_url %>
    </td>

    <td scope="col">
      <%= short_url(link) %>
    </td>

    <td scope="col">
      <%= link.clicks %>
    </td>

    <%if params[:action] == 'index' %>
      <td scope="col">
        <%= link_to "Show", link %>
      </td>
    <%end%>
  </tr>
</div>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Show this link", @link %> |
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/index.html.erb
<div id="links" class="container">
  <h1>Links</h1>
  <%= link_to "New link", new_link_path %>

  <table class="table">
    <thead>
      <tr>
        <th scope="col"><strong>Main url</strong></th>
        <th scope="col"><strong>Token</strong></th>
        <th scope="col"><strong>Clicks</strong></th>
        <th scope="col"><strong>Action</strong></th>
      </tr>
    </thead>
    <tbody>
      <% @links.each do |link| %>
        <%= render link %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/links/new.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">New link</h5>
        <%= render "form", link: @link %>
      <br>

      <div>
        <%= link_to "Links", links_path %>
      </div>
    </div>
  </div>
</div>

app/views/links/show.html.erb
<div class="container">
  <div>
    <%= link_to "Back", links_path %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><strong>Main url</strong></th>
        <th scope="col"><strong>Token</strong></th>
        <th scope="col"><strong>Clicks</strong></th>
      </tr>
    </thead>
    <tbody>
      <%= render @link %>
    </tbody>
  </table>
</div>